# Numpy

https://numpy.org/

## What is it? 
- Numpy is a Python library used for working with arrays
- Numpy is the fundamental package for scientific computing in Python


## Why do we care? 
- Numpy is one of the main reasons why Python is so powerful and popular for scientific computing
- Super fast. Numpy arrays are implemented in C, which makes numpy very fast.
- The arrays allows for vectorized operations

## Show us! 

### Create a 1D array

#### create a list
format: list()

In [1]:
#create a list
my_list = [1, 2, 3, 4]

In [2]:
#whats the type


In [3]:
#what is dtype


In [4]:
#whats the shape


#### create an array
format: np.array()

In [5]:
#import numpy
import numpy as np

In [6]:
#create the array
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4])

In [7]:
#whats the type
type(my_array)

numpy.ndarray

In [8]:
#whats the shape
my_array.shape

(4,)

In [9]:
my_array.dtype

dtype('int64')

#### access elements of our new array

In [10]:
my_array[0]

1

In [11]:
my_array[3]

4

In [12]:
my_array[-1]

4

#### slice the array

In [13]:
my_array[1:] # inclusive for the first element

array([2, 3, 4])

In [14]:
my_array[:2] # exclusive for the last element

array([1, 2])

#### create an array from 1 to 100

In [15]:
#np.array(?)
a = np.array(range(1, 101))
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [16]:
#access single element
a[0]

1

In [17]:
#slice the array! 
a[50:70]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70])

### Create a 2D array

In [18]:
#build a list of lists
matrix = [[1, 2, 3],
[4, 5, 6], 
[7, 8, 9], 
[10, 11, 12]]

In [19]:
type(matrix)

list

In [20]:
#turn it into an array! 
matrix_array = np.array(matrix)

In [21]:
#type
type(matrix_array)

numpy.ndarray

#### access elements

In [22]:
matrix_array.shape

(4, 3)

In [23]:
matrix_array[1, 2] # accesed the index position 1 which is the second row and the index position in that list 
# 2 which is the third number = 6

6

In [24]:
matrix_array[-1, -1]

12

### Descriptive Stats

In [25]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [26]:
# can either use a method or a function

In [27]:
# lets use a method

In [28]:
a.min()

1

In [29]:
a.max()

100

In [30]:
a.std()

28.86607004772212

In [31]:
a.sum()

5050

In [32]:
a.mean()

50.5

#### using methods: the method is called on the numpy object

In [33]:
matrix_array.mean()

6.5

In [34]:
matrix_array.min()

1

In [35]:
matrix_array.std()

3.452052529534663

#### using functions: using numpy to call functions

In [36]:
np.max(a)

100

In [37]:
np.std(a)

28.86607004772212

In [38]:
np.mean(a)

50.5

In [39]:
np.sum(a)

5050

In [40]:
np.sum(matrix_array)

78

In [41]:
np.max(matrix_array)

12

### Array of Booleans! 

### Boolean Masks

1. create an array
2. make a list of booleans (mask)
3. combine

    format: array [ list of booleans ] 

In [42]:
#pull back our small array
my_array

array([1, 2, 3, 4])

In [43]:
#make list of booleans aka our mask
mask = [True, False, False, True]

In [44]:
#combine them 
my_array[mask] # it returns the values that correspond with True. This is known as True masking

array([1, 4])

In [45]:
np.array(mask).sum() # it equals 2 because True = 1 and False = 0

2

#### how else can we get our array of boolean values?

In [46]:
my_array

array([1, 2, 3, 4])

In [47]:
#write a conditional with the array
my_array == 4

array([False, False, False,  True])

In [48]:
my_array[mask]

array([1, 4])

In [49]:
mask = my_array > 2
mask

array([False, False,  True,  True])

In [50]:
my_array[mask]

array([3, 4])

#### make and apply our boolean mask

In [51]:
#format: array_name [ list_of_booleans ]


In [52]:
matrix_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
mask = (matrix_array > 3)
mask

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [54]:
matrix_array[mask] # returns all values in matrix that are greater than 3 in a 1D array

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
# whaty about with mult conditions?
mask = (my_array == 3) & (my_array ==4)
mask

array([False, False, False, False])

In [56]:
my_array[mask]

array([], dtype=int64)

In [57]:
new_mask = (my_array == 2) | (my_array == 7)

In [58]:
my_array[new_mask]

array([2])

#### cool! can we just do it with a list instead of an array?

In [59]:
#pull back our initial list
my_list

[1, 2, 3, 4]

In [60]:
my_list == 4

False

In [61]:
# no it does not work on a list, must be an array

In [62]:
mask

array([False, False, False, False])

In [63]:
#create a array of booleans
new_mask = [True, False, True, True]

In [64]:
#apply an array of booleans to a list
my_list[new_mask]

TypeError: list indices must be integers or slices, not list

#### let's bring it back to arrays and make them bigger

In [ ]:
#array
a

In [ ]:
#mask
mask = a >= 90
mask

In [ ]:
#boolean mask
a[mask]

#### shortcut?

In [ ]:
a[a>=90]

#### what if we wanted to check two conditions?

In [ ]:
# note the parenthesis
# also note that we're using & instead of and


In [ ]:
mask = (a > 5) & (a < 75)

In [ ]:
a[mask]

#### what if we wanted the opposite of our mask?

In [ ]:
# the ~ notates the opposite of
~mask

In [ ]:
a[~mask]

In [ ]:
my_array

In [ ]:
matrix

In [ ]:
new_list = []

for i in list(matrix):
    new_list.extend(i)

new_list

## Vectorization Operations
- makes looping over math so easy and fast!

### Add one to every element

#### hard way: doing it in a list

In [ ]:
my_list

In [65]:
#using a for loop
new_list = []

for i in my_list:
    new_list.append(i + 1)

new_list


[2, 3, 4, 5]

In [66]:
#using a list comprehension
[i+1 for i in my_list]

[2, 3, 4, 5]

#### easy way: doing it with an array

In [67]:
my_array

array([1, 2, 3, 4])

In [68]:
#using vectorization operations
my_array + 1

array([2, 3, 4, 5])

### more operations

In [69]:
my_array * 2

array([2, 4, 6, 8])

In [70]:
my_array ** 2

array([ 1,  4,  9, 16])

In [71]:
my_array / 10

array([0.1, 0.2, 0.3, 0.4])

In [72]:
my_array % 2 

array([1, 0, 1, 0])

In [73]:
np.log(my_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [74]:
(my_array / 3) + 5

array([5.33333333, 5.66666667, 6.        , 6.33333333])

### show us the speed

In [77]:
#make a really big array
big_array = np.array(range(1_000_000))
big_array

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [79]:
%%timeit
big_array ** 2
# times the commuting time

661 µs ± 40.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [81]:
#make a really big list
big_list = list(big_array)

In [83]:
# %%timeit
for x in big_list:
    x**2

In [84]:
%%timeit

for x in big_list:
    x**2
    
## it takes much longer to do this than the array

95.6 ms ± 2.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Numpy ways to create arrays

#### full of zeros

In [85]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [90]:
zeros = np.zeros((10, 10))

#### full of ones

In [94]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [95]:
len(np.ones(10_000))

10000

#### full of whatever you want 

In [96]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [97]:
np.full(10, True)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [98]:
np.full((10, 3), 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

#### a quicker way to make a range

In [99]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### an array of random integers

In [101]:
#np.random.randint()
np.random.randint(2, 20)

13

In [102]:
np.random.randint?


In [103]:
np.random.randint(1, 100, 5)

array([13, 67, 95, 95, 50])

#### an array of random numbers from the standard distribution

In [104]:
#np.random.randn()
np.random.randn()

0.8141531183740524

In [105]:
np.random.randn?


In [106]:
np.random.randn(1_000_000)

array([-0.41398577, -1.14718909,  1.01151121, ...,  0.29804691,
       -0.55171555,  1.2693055 ])