In [2]:
import numpy as np

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [5]:
# How many negative numbers are there?

mask = a < 0

In [12]:
mask

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [15]:
np.array(mask).sum()
# there are 4 negative numbers in the array

4

In [ ]:
# How many positive numbers are there?

In [16]:
np.array(~mask).sum()
# there are 8 positive numbers in the array

8

In [ ]:
# 3. How many even positive numbers are there?

In [17]:
pos_even_mask = (a >= 0) & (a % 2 ==0)

In [18]:
np.array(pos_even_mask).sum()
# there are 6 even positive numbers in the array

6

In [ ]:
# 4. If you were to add 3 to each data point, how many 
# positive numbers would there be?

In [178]:
a_plus_3 = a + 3
a_plus_3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [179]:
len(a_plus_3[a_plus_3>=0])
# there are 10 positive numbers in a + 3 array

10

In [ ]:
# 5. If you squared each number, what would the new mean 
# and standard deviation be?

In [27]:
a_squar = a ** 2
a_squar

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [29]:
np.mean(a_squar)

74.0

In [30]:
np.std(a_squar)

144.0243035046516

In [ ]:
# 6. A common statistical operation on a dataset is centering.
# This means to adjust the data such that the mean of the 
# data is 0. This is done by subtracting the mean from each 
# data point. Center the data set. See this link for more on
# centering.

In [32]:
a_mean = np.mean(a)

In [34]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [33]:
a_cent = a - a_mean
a_cent

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [ ]:
# 7. Calculate the z-score for each data point.

In [36]:
a_std = np.std(a)

In [37]:
a_zscore = []

for x in a:
    a_zscore.append((x - a_mean) / a_std)

a_zscore
    

[0.12403473458920847,
 0.8682431421244593,
 1.116312611302876,
 2.4806946917841692,
 -0.6201736729460423,
 -0.49613893835683387,
 -0.3721042037676254,
 -0.3721042037676254,
 -0.3721042037676254,
 -1.116312611302876,
 0.0,
 -1.2403473458920846]

In [39]:
a_zarray = np.array(a_zscore)

In [41]:
a_zarray

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [ ]:
# 8. 

In [42]:
# Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [43]:
type(a)

list

In [65]:
a = np.array(a)

In [181]:
# Exercise 1 - Make a variable called sum_of_a to hold the 
# sum of all the numbers in above list
sum(a)

55

In [188]:
# Exercise 2 - Make a variable named min_of_a to hold the 
# minimum of all the numbers in the above list
min_of_a = min(a)

In [187]:
# Exercise 3 - Make a variable named max_of_a to hold the 
# max number of all the numbers in the above list
max_of_a = np.max(a)

In [186]:
# Exercise 4 - Make a variable named mean_of_a to hold the 
# average of all the numbers in the above list
mean_of_a = np.mean(a)

In [70]:
# Exercise 5 - Make a variable named product_of_a to hold 
# the product of multiplying all the numbers in the above 
# list together
product_of_a = np.prod(a)

In [73]:
# Exercise 6 - Make a variable named squares_of_a. It 
# should hold each number in a squared like 
# [1, 4, 9, 16, 25...]
squares_of_a = a ** 2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [78]:
# Exercise 7 - Make a variable named odds_in_a. It should 
# hold only the odd numbers

odd_mask = (a % 2 != 0)
odd_mask

odds_ina = a[odd_mask]

In [79]:
# Exercise 8 - Make a variable named evens_in_a. It should 
# hold only the evens.

even_mask = (a % 2 == 0)
evens_ia_a = a[even_mask]

In [81]:
## Setup 2: Consider what it would take to find the sum, min,
# max, average, sum, product, and list of squares for this 
# list of two lists.

b = [
    [3, 4, 5],
    [6, 7, 8]
]


In [82]:
np.sum(b)

33

In [83]:
np.min(b)

3

In [85]:
np.max(b)

8

In [86]:
np.mean(b)

5.5

In [87]:
np.prod(b)

20160

In [88]:
b_list = []

for i in list(b):
    b_list.append(i)

b_list

[[3, 4, 5], [6, 7, 8]]

In [92]:
type(b)

list

In [95]:
b = np.array(b)

In [96]:
b_squar = b ** 2
b_squar

array([[ 9, 16, 25],
       [36, 49, 64]])

In [97]:
# Exercise 1 - refactor the following to use numpy. Use 
# sum_of_b as the variable. **Hint, you'll first need to 
# make sure that the "b" variable is a numpy array**
# sum_of_b = 0
# for row in b:
    # sum_of_b += sum(row)

In [98]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [100]:
sum_of_b = np.sum(b)
sum_of_b

33

In [ ]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

In [101]:
min_of_b = np.min(b)
min_of_b

3

In [102]:
# Exercise 3 - refactor the following maximum calculation to 
# find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = np.max(b)
max_of_b

8

In [103]:
# Exercise 4 - refactor the following using numpy to find 
# the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = np.mean(b)
mean_of_b

5.5

In [104]:
# Exercise 5 - refactor the following to use numpy for 
# calculating the product of all numbers multiplied together.
#product_of_b = 1
#for row in b:
    #for number in row:
        #product_of_b *= number

product_of_b = np.prod(b)
product_of_b

20160

In [107]:
# Exercise 6 - refactor the following to use numpy to find 
# the list of squares 
#squares_of_b = []
#for row in b:
    #for number in row:
        #squares_of_b.append(number**2)
        
b_squar = b ** 2
b_squar = list(b_squar)
b_squar

[array([ 9, 16, 25]), array([36, 49, 64])]

In [109]:
# Exercise 7 - refactor using numpy to determine the 
# odds_in_b
#odds_in_b = []
#for row in b:
    #for number in row:
       # if(number % 2 != 0):
           # odds_in_b.append(number)

odd_mask = (b % 2 != 0)
b[odd_mask]

array([3, 5, 7])

In [110]:
# Exercise 8 - refactor the following to use numpy to filter 
# only the even numbers
#evens_in_b = []
#for row in b:
    #for number in row:
        #if(number % 2 == 0):
            #evens_in_b.append(number)
b[~odd_mask]

array([4, 6, 8])

In [111]:
# Exercise 9 - print out the shape of the array b.

b.shape

(2, 3)

In [112]:
# Exercise 10 - transpose the array b.

np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [ ]:
# Exercise 11 - reshape the array b to be a single list of 6 
# numbers. (1 x 6)

In [114]:
np.reshape(b, (1,6))

array([[3, 4, 5, 6, 7, 8]])

In [115]:
# Exercise 12 - reshape the array b to be a list of 6 lists, 
# each containing only 1 number (6 x 1)
np.reshape(b, (6, 1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [116]:
## Setup 3

c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [118]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Exercise 1 - Find the min, max, sum, and product of c.

In [119]:
np.min(c)

1

In [120]:
np.max(c)

9

In [121]:
np.sum(c)

45

In [122]:
np.prod(c)

362880

In [123]:
# Exercise 2 - Determine the standard deviation of c.
np.std(c)

2.581988897471611

In [ ]:
# Exercise 3 - Determine the variance of c.

In [124]:
np.var(c)

6.666666666666667

In [125]:
# Exercise 4 - Print out the shape of the array c
np.shape(c)

(3, 3)

In [126]:
# Exercise 5 - Transpose c and print out transposed result.
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [128]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [144]:
# # Exercise 7 - Write the code necessary to sum up the result
# of c times c transposed. Answer should be 261

c_times_c = c * (np.transpose(c))
ctrans = np.transpose(c_times_c)
np.sum(ctrans)

261

In [145]:
# Exercise 8 - Write the code necessary to determine the 
# product of c times c transposed. Answer should be 
# 131681894400.

np.prod(ctrans)

131681894400

In [146]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [147]:
type(d)

list

In [153]:
np.array(d)

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [149]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [150]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [151]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [166]:
# Exercise 4 - Find all the negative numbers in d
d = np.array(d)

In [168]:
d[d<0]

array([-90, -30, -45, -45])

In [169]:
# Exercise 5 - Find all the positive numbers in d
d[d>=0]

array([ 90,  30,  45,   0, 120, 180,  45, 270,  90,   0,  60,  45,  90,
       180])

In [171]:
# Exercise 6 - Return an array of only the unique numbers 
# in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [173]:
# Exercise 7 - Determine how many unique numbers there are 
# in d.
len(np.unique(d))

11

In [174]:
# Exercise 8 - Print out the shape of d.
np.shape(d)

(3, 6)

In [176]:
# Exercise 9 - Transpose and then print out the shape of d.

trans_d = np.transpose(d)
np.shape(trans_d)

(6, 3)

In [177]:
# Exercise 10 - Reshape d into an array of 9 x 2
np.reshape(d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])